version: "3"
services:
  consumer:
    image: calculatorserviceclient
    ports:
      - "8093:8080"
    networks:
      - consumer-producer
    depends_on:
      - producer
 
  producer:
    image: rahulvaish/springbootcalculatorservice
    ports:
      - "8097:8080"
    networks:
      - consumer-producer 

networks:
  consumer-producer: